---
apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: wood87
  region: eu-west-2

nodeGroups:
  - name: ng-1122
    instanceType: t2.xlarge #t2.medium
    desiredCapacity: 2
    volumeSize: 15
    # ssh:
    #   allow: true
    #   privateKeyPath: 'C:\\MyDesktop\\ADV-IT\\Key_ssh\\wood8-key-london-2.pem'